variables:
  PYENV: "vac2fost-test-env"
  SLURM_CMD: "srun --exclusive=user -p gitlab --cpus-per-task 1"
cache:
  paths:
    - deps/
  untracked: false

before_script:
  - hostname
  - pwd
  - echo $USER
  - echo $GITLAB_USER_ID
  - echo $GITLAB_USER_NAME
  - echo $GITLAB_USER_LOGIN
  - module load userspace/170135
  - module load python/3.6.3_anaconda3
  - export PATH=$PATH:`pwd`/deps
  - export MCFOST_UTILS=`pwd`/deps/mcfost_utils

stages:
  - build
  - install
  - unit_tests
  - integration_tests
  - final

update_pyenv:
  stage: build
  script:
    - export CONDA_INST="--name $PYENV --file environment.yml --channel conda-forge --yes"
    - $SLURM_CMD conda create $CONDA_INST || $SLURM_CMD conda install $CONDA_INST

download_deps:
  stage: build
  script:
    - $SLURM_CMD bash dl_deps.sh

install_mcfost:
  stage: build
  script:
    - mkdir deps || echo "skip mkdir"
    - cd deps/
    - $SLURM_CMD wget http://ipag.osug.fr/public/pintec/mcfost/linux/mcfost.tgz
    - tar xvzf mcfost.tgz
    - chmod +x mcfost
    - mkdir -p $MCFOST_UTILS || echo "skip mkdir"
    - $SLURM_CMD ./mcfost -setup
    - yes | ./mcfost ref3.0.para && rm -fr data_th # agree to licence...
    - cd ../
    - which mcfost
    - mcfost -version

install_pymodules:
  stage: install
  script:
    - source activate $PYENV
    - $SLURM_CMD pip install `pwd`/deps/vtk_vacreader-project
    - $SLURM_CMD pip install .

unitests:
  stage: unit_tests
  script:
    - source activate $PYENV
    - $SLURM_CMD pytest tests/unit

mcfost_grid:
  stage: unit_tests
  script:
    - source activate $PYENV
    - $SLURM_CMD pytest tests/test_mcfost_grid.py

misc_intest:
  stage: integration_tests
  script:
    - source activate $PYENV
    - $SLURM_CMD pytest tests/int

shell:
  stage: integration_tests
  script:
    - source activate $PYENV
    - export ROOTDIR=`pwd`
    - $SLURM_CMD bash tests/test_shell.sh

regression:
  stage: integration_tests
  script:
    - source activate $PYENV
    - $SLURM_CMD pytest tests/test_regression.py

code_quality:
  stage: final
  script:
    - source activate $PYENV
    - pylint --rcfile .pylintrc vac2fost/vac2fost.py

run_demo:
  stage: final
  script:
    - source activate $PYENV
    - $SLURM_CMD python docs/demo.py

