variables:
  PYENV: "vac2fost-test-env"
  SLURM_CMD: "srun --exclusive=user -p gitlab --cpus-per-task 1 --ntasks 1"
cache:
  paths:
    - deps/
  untracked: false

before_script:
  - hostname
  - pwd
  - echo $USER
  - echo $GITLAB_USER_ID
  - echo $GITLAB_USER_NAME
  - echo $GITLAB_USER_LOGIN
  - module load userspace/OCA
  - module load python/3.6.3_anaconda3
  - export PATH=$PATH:`pwd`/deps
  - export MCFOST_UTILS=`pwd`/deps/mcfost_utils

stages:
  - build
  - install
  - unit_tests
  - integration_tests
  - final
  - clean

install or update pyenv:
  stage: build
  script:
    - export CONDA_INST="--name $PYENV --file environment.yml --channel conda-forge --yes"
    - $SLURM_CMD conda create $CONDA_INST || $SLURM_CMD conda install $CONDA_INST

download private dependencies:
  stage: build
  script:
    - $SLURM_CMD dl_deps.sh

install mcfost:
  stage: build
  script:
    - rm -fr $HOME/.mcfost
    - mkdir deps || echo "skip mkdir"
    - cd deps/
    - $SLURM_CMD wget http://ipag.osug.fr/public/pintec/mcfost/linux/mcfost.tgz
    - tar xvzf mcfost.tgz
    - chmod +x mcfost
    - mkdir -p $MCFOST_UTILS || echo "skip mkdir"
    - $SLURM_CMD ./mcfost -setup
    - mkdir $HOME/.mcfost
    - touch $HOME/.mcfost/accept_disclaimer_3.0.35
    - cd ../
    - which mcfost
    - mcfost -version

install private dependencies:
  stage: install
  script:
    - source activate $PYENV
    - which pip
    - $SLURM_CMD pip install `pwd`/deps/vtk_vacreader-project
    - $SLURM_CMD pip install .

unit:
  stage: unit_tests
  script:
    - source activate $PYENV
    - $SLURM_CMD pytest tests/unit

integration:
  stage: integration_tests
  script:
    - source activate $PYENV
    - $SLURM_CMD pytest tests/int

shell:
  stage: integration_tests
  script:
    - source activate $PYENV
    - export VAC2FOST_INSTALL_DIR=$(pwd)
    - $SLURM_CMD bash tests/test_shell.sh

regression:
  stage: integration_tests
  script:
    - source activate $PYENV
    - $SLURM_CMD pytest tests/test_regression.py

check code quality:
  stage: final
  script:
    - source activate $PYENV
    - conda install flake8 --yes
    - flake8 vac2fost/*.py
    - pylint --rcfile .pylintrc vac2fost/*.py

run demo:
  stage: final
  script:
    - source activate $PYENV
    - $SLURM_CMD python docs/demo.py
