#!/usr/bin/env bash
# -------------------------------------------
# generate an image with mcfost with a
# density file input.
#
# This is a demo script.
# -------------------------------------------

DENS=hd142527_dusty0000.fits
CONF=mcfost_conf.para
OUT=tmp/mcfost_out

[ ! -d "$OUT" ] && mkdir $OUT

if [ ! -f "$DENS" ]; then
    echo "target file $DENS not found, aborting script."
    echo "(this input file should be generated by test_api.py)"
    exit 1
fi

if [ ! -f "$CONF" ]; then
    echo "$CONF not found, aborting script."
    echo "(this input file should be generated by test_api.py)"
    exit 1
fi

call="mcfost $CONF -density_file $DENS -root_dir $OUT -3D"
eval $call

# no way to catch an error from MCFOST currently...
eval $call -img 1300
